### ISSUE TITLE
Improve About Section on Website

### ISSUE THREAD

**Issue by ajaynegi33** [ajaynegi45/Investment-Calculator#2]
**Issue Description:**
- Improvement to the "About" section on our website to provide users with a more comprehensive understanding of the website's purpose and functionality. Currently, the section lacks detailed information, and I believe a clearer description will enhance the user experience.

Here are some suggestions for the improved "About" section:

1. **Introduction**: Begin with a brief but engaging introduction that captures the essence of the website. Explain what the website offers and its primary goal.

2. **Functionality**: Describe how the Dividend Income Investment Calculator works. Explain that users can input their desired annual income and the dividend yield of a share to calculate the required investment.

3. **Benefits**: Highlight the benefits of using this calculator. Mention how it can help users plan their investments more effectively and make informed financial decisions.

4. **User-Friendly**: Emphasize that the website is user-friendly and easy to navigate. Mention any user-friendly features or design elements that enhance the experience.

5. **Accuracy**: Assure users of the accuracy of the calculations provided by the calculator. Explain any data sources or methodologies used to ensure precision.

6. **Contact Information**: Provide contact information or a link to a Contact Us page in case users have questions or need assistance.

7. **Feedback**: Encourage users to provide feedback to help us improve the website further.

By making these improvements, we aim to create a more informative and user-friendly "About" section that enhances the overall user experience and helps visitors better understand the website's purpose and functionality.

Thank you for considering this enhancement request.

**Comment by avishkaindula** [comment]
Hi @ajaynegi45 I would like to work on this issue

**Comment by ajaynegi33** [comment]
> Hi @ajaynegi45 I would like to work on this issue

**Assignee:** @avishkaindula 

Hi @avishkaindula ,

Thank you for expressing your interest in working on the "Improve About Section on Website " issue. I'm delighted to inform you that I have assigned this issue to you. Create new about page and link that with home page. Your willingness to contribute to our project and Improve About Section on Website  is much appreciated.

Feel free to start working on the page's content and design, and if you have any questions or need assistance during the process, please don't hesitate to reach out. We eagerly anticipate your work on creating an informative and visually appealing "About" page for our website.

**Comment by avishkaindula** [comment]
@ajaynegi45 I've created a pull request. Can you explain me how this pr would be eligible for Hacktoberfest? This is the first time I'm doing this and I don't have much of an idea.

**Comment by roniskywalker** [comment]
Hello [ajaynegi45](https://github.com/ajaynegi45), I have fixed this issue. Please do check.

**Comment by ajaynegi33** [comment]
> @ajaynegi45 I've created a pull request. Can you explain me how this pr would be eligible for Hacktoberfest? This is the first time I'm doing this and I don't have much of an idea.

I have added dark and light mode in it. It getting hide behind the navbar. resolve this issue

**Comment by avishkaindula** [comment]
Sure thing. I'm working on it.
